name: Publish PlatformIO - Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-platformio-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Login to PlatformIO
        run: pio account login -u ${{ secrets.PLATFORMIO_USERNAME }} -p ${{ secrets.PLATFORMIO_PASSWORD }}
      
      - name: Publish Package
        run: pio pkg publish
        
      - name: Create Package
        run: pio pkg pack -o ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz

